version: "3.8"
services:
  app:
    build: .
    container_name: lib-server
    ports:
      - "4444:4444"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
