version: "3.8"

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - SUPABASE_PUBLIC_ANON_KEY=${SUPABASE_PUBLIC_ANON_KEY}
    volumes:
      - .:/usr/src/app
    command: ["bun", "dist/index.js"]

  app-dev:
    build: .
    environment:
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - SUPABASE_PUBLIC_ANON_KEY=${SUPABASE_PUBLIC_ANON_KEY}
    volumes:
      - .:/usr/src/app
    command: ["bun", "--watch", "src/index.ts"]
