name: Telegram Bot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and run Docker Compose
      - name: Build and run services
        run: |
          docker-compose up --build -d
